version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./tests/mocked_tests.py
          name: Mocked Tests

workflows:
  version: 2.1
  test_deploy:
    jobs:
      - build-and-test